name: msdxc

on:
  workflow_dispatch:
    inputs:
      opencv-version:
        description: dxc
        required: true
        default: 4.5.2

jobs:
  publish_windows_x64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
            repository: Klanly/NoShiTx64dbg
            submodules: true

      - name: tocmd
        run: |
          build.bat x64
          release.bat
        shell: cmd
      
      
      - name: Upload AssetRipper Windows x64
        uses: actions/upload-artifact@v3
        with:
          name: x86rel
          path: D:\a\buildcv\buildcv\release
          if-no-files-found: error

 
